config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from view_it.search.views import home_page_view

urlpatterns = [
    path("", view=home_page_view, name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("@", include("view_it.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("video/", include("view_it.videos.urls", namespace="videos")),
    path("search/", include("view_it.search.urls", namespace="search")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

view_it/search/urls.py
from django.urls import path

from .views import search_view

app_name = "search"
urlpatterns = [
    path("", view=search_view, name="index"),
]

view_it/users/urls.py
from django.urls import path

from view_it.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

view_it/videos/urls.py
from django.urls import path

from .views import video_detail_view, video_update_view, video_upload_view

app_name = "videos"
urlpatterns = [
    path("upload/", view=video_upload_view, name="upload"),
    path("~update/<slug:url_slug>/", view=video_update_view, name="update"),
    path("<slug:url_slug>/", view=video_detail_view, name="detail"),
]

view_it/search/models.py
import meilisearch
from django.conf import settings
from django.contrib.auth import get_user_model

from view_it.videos.models import Videos

User = get_user_model()


# The Search class handles operations related to MeiliSearch
class Search:
    # Initialize MeiliSearch client with provided host in settings
    def __init__(self):
        self.client = meilisearch.Client(settings.MEILI_HOST)

    # Get or create a search index. An index is where the documents are stored.
    def get_index(self, index_name):
        try:
            # Get all indexes
            indexes = self.client.get_indexes()
        except self.client.errors as errors:
            # Raise any errors
            raise errors

        # Look for the required index in the retrieved indexes
        for index in indexes["results"]:
            if index.uid == index_name:
                return index

        # If the index doesn't exist, create a new one
        self.client.create_index(index_name)
        index = self.client.index(index_name)

        # Update searchable attributes based on the index
        if index_name == "users":
            index.update_searchable_attributes(["username"])
        elif index_name == "videos":
            index.update_searchable_attributes(
                [
                    "title",
                    "description",
                ]
            )

        return index

    # Add a document to the index. A document is a record in MeiliSearch.
    def add_document_to_index(self, index_name, document):
        index = self.get_index(index_name=index_name)
        index.add_documents([document], "id")
        # Return the task. A task in MeiliSearch represents an asynchronous operation.
        return self.client.get_task(0)

    # Add a video to the 'videos' index
    def add_video(self, video_id: int):
        video = Videos.objects.get(id=video_id)

        # Prepare the document
        document = {
            "id": video.id,
            "title": video.title,
            "url": str(video.get_absolute_url()),
            "description": video.description if video.description else "",
            "thumbnail": video.thumbnail.url if video.thumbnail else "",
            "user": video.user.username,
        }

        # Add the document to the 'videos' index
        return self.add_document_to_index(index_name="videos", document=document)

    # Add a user to the 'users' index
    def add_user(self, user_id: int):
        user = User.objects.get(id=user_id)

        # Prepare the document
        document = {
            "id": user.id,
            "username": user.username,
            "description": user.channel_description if user.channel_description else "",
            "avatar": user.avatar.url if user.avatar else "",
            "url": str(user.get_absolute_url()),
        }

        # Add the document to the 'users' index
        return self.add_document_to_index(index_name="users", document=document)

view_it/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField, FileField, TextField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .validators import validate_avatar_file_type, validate_unique_email


class User(AbstractUser):
    """
    Default custom user model for View It.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    name = CharField(_("Name of User"), blank=True, max_length=255)

    email = EmailField(
        _("email address"),
        unique=True,
        validators=[validate_unique_email],
        help_text=_("Required. Must be an unique and valid email address."),
    )

    username = CharField(
        _("Username"),
        max_length=30,
        unique=True,
        help_text=_("Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only."),
    )

    avatar = FileField(
        _("Avatar"),
        upload_to="avatars/%Y/%m/%d/%H/",
        blank=True,
        validators=[validate_avatar_file_type],
        help_text="Supported file types are: .jpg, .jpeg, .png, and .gif",
    )

    channel_description = TextField(_("Channel Description"), blank=True)

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

view_it/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

view_it/videos/forms.py
from django import forms

from view_it.videos.models import Videos


class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Videos
        fields = ["title", "description", "file", "thumbnail", "status"]

view_it/search/views.py
from typing import Any

from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView

from view_it.videos.models import Videos


class HomePageView(SuccessMessageMixin, TemplateView):
    template_name = "pages/home.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        context["public_videos"] = (
            Videos.objects.filter(status="public").order_by("-uploaded_timestamp").select_related("user")[:20]
        )

        return context


home_page_view = HomePageView.as_view()


class SearchView(SuccessMessageMixin, TemplateView):
    template_name = "search/videos.html"


search_view = SearchView.as_view()

view_it/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from view_it.videos.models import Videos

User = get_user_model()


class UserDetailView(DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        public_videos = Videos.objects.filter(user=user, status="public").order_by("-uploaded_timestamp")
        private_videos = Videos.objects.filter(user=user, status="private").order_by("-uploaded_timestamp")
        context["public_videos"] = public_videos
        context["private_videos"] = private_videos
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["avatar", "username", "channel_description"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

view_it/videos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView, UpdateView

from .forms import VideoUploadForm
from .models import Videos


class VideoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Videos
    form_class = VideoUploadForm
    template_name = "videos/upload_video.html"
    success_message = _("Video successfully uploaded!")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


video_upload_view = VideoCreateView.as_view()


class VideoDetailView(DetailView):
    model = Videos
    slug_field = "url_slug"
    slug_url_kwarg = "url_slug"
    template_name = "videos/view_video.html"


video_detail_view = VideoDetailView.as_view()


class VideoUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Videos
    slug_field = "url_slug"
    slug_url_kwarg = "url_slug"
    fields = ["title", "description", "thumbnail", "status"]
    template_name = "videos/update_video.html"
    success_message = _("Information successfully updated!")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return reverse("videos:detail", kwargs={"url_slug": self.object.url_slug})

    def get_object(self):
        return Videos.objects.filter(url_slug=self.kwargs["url_slug"], user=self.request.user.id).first()


video_update_view = VideoUpdateView.as_view()

view_it/templates/base.html
{% load static i18n %}{% load render_bundle from webpack_loader %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}View It{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="FOSS video hosting platform">
    <meta name="author" content="Julio Fajardo">

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    {% render_bundle 'project' 'css' %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      {% render_bundle 'vendors' 'js' attrs='defer' %}

      <!-- place project specific Javascript in this file -->
      {% render_bundle 'project' 'js' attrs='defer' %}

    {% endblock javascript %}

    {% block template_javascript %}
      <!-- place template specific Javascript using this tag -->
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@8.0.0/themes/satellite-min.css" integrity="sha256-p/rGN4RGy6EDumyxF9t7LKxWGg6/MZfGhJM/asKkqvA=" crossorigin="anonymous">

  </head>

  <body class="container bg-black text-light">
      <header>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-dark px-4 py-3 shadow">
            <!-- Logo -->
            <a class="navbar-brand ms-lg-5 mb-lg-0 mb-4 text-light" href="{% url 'home' %}">
              <img src="" class="h-8" alt="View.it">
            </a>
            <!-- Navbar toggle -->
            <button class="navbar-toggler mb-4" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars text-white" style="font-size:1.2rem;"></i>
            </button>
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <!-- Nav -->
              <div class="navbar-nav col-lg-6 mx-auto">
                  <div class="input-group">
                    <div id="meili" class="w-100"></div>
                    <div id="meili-results" class="w-100 position-absolute" style="z-index: 5; top:2.6rem"></div>
                  </div>
              </div>
              {% if request.user.is_authenticated %}
                <div class="dropdown navbar-nav ps-lg-5 mt-lg-0 mt-3">
                  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.username }}
                  </button>
                  <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">{% translate "Your Channel" %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'videos:upload' %}">{% translate "Upload a Video" %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:update' %}">{% translate "Edit Channel Info" %}</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a></li>
                  </ul>
                </div>
              {% else %}
                <!-- Right navigation -->
                <div class="navbar-nav ms-lg-5 mt-lg-0 mt-3">
                  <a class="nav-item nav-link text-light" href="{% url 'account_login' %}">
                    {% translate "Sign in" %}
                  </a>
                </div>
                <!-- Action -->
                <div class="navbar-nav ms-lg-5 mt-lg-0 mt-3 text-light">
                  <a class="nav-item nav-link text-light" href="{% url 'account_signup' %}" >
                    {% translate "Register" %}
                  </a>
                </div>
              {% endif %}
            </div>
        </nav>
      </header>

    <div>
      {% if messages %}
        <div class="container">
          {% for message in messages %}
            <div class="container fixed-top alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}" style="margin-top: 6rem;">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        </div>
      {% endif %}

      <div style="margin-top: 6rem">
        {% block content %}
          <p>Use this document as a way to quick start any new project.</p>
        {% endblock content %}
      </div>

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */});
    </script>
    {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>